"""Distribution metadata resolution: version and default API server.

The authoritative values live in ``pyproject.toml`` at the repository
root. Packaged builds embed them via a generated ``_build_meta.py`` module
(created by ``tools/build.py``); source runs fall back to parsing the
``pyproject.toml`` next to the client bundle.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

#: Path of the injected build metadata, generated by tools/build.py.
_BUILD_META_PATH = Path(__file__).resolve().parent / "_build_meta.py"

#: Fallback API server for development runs without a configured default.
_LOCAL_API_SERVER = "http://127.0.0.1:7999"


def _build_meta_namespace() -> dict:
    """Return the injected build metadata namespace, or an empty dict.

    The file is generated by tools/build.py and only exists in packaged
    executables; it carries ``__version__`` and ``default_api_server``.
    """
    if not _BUILD_META_PATH.is_file():
        return {}
    import runpy

    return runpy.run_path(str(_BUILD_META_PATH))


def _pyproject() -> dict:
    """Return the parsed root pyproject.toml, or an empty dict."""
    try:
        root = Path(__file__).resolve().parent.parent.parent.parent
        with (root / "pyproject.toml").open("rb") as f:
            return tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError):
        return {}


def app_version() -> str:
    """Return the application version string.

    Prefers the build-time generated ``_build_meta.py`` module (present in
    packaged executables); falls back to reading ``pyproject.toml`` from
    the repository root during source runs.
    """
    version = _build_meta_namespace().get("__version__")
    if version:
        return version
    return _pyproject().get("project", {}).get("version") or "unknown"


def default_api_server() -> str:
    """Return the default API server URL.

    Prefers the build-time generated ``default_api_server`` (from the
    ``[tool.build]`` section of pyproject.toml, injected into packaged
    executables); falls back to the local development server when unset.
    """
    server = _build_meta_namespace().get("default_api_server")
    if server:
        return server
    return (
        _pyproject()
        .get("tool", {})
        .get("build", {})
        .get("default_api_server")
        or _LOCAL_API_SERVER
    )


if __name__ == "__main__":
    sys.stdout.write(f"version={app_version()} api_server={default_api_server()}\n")
