# Copyright (c) 2026, Harry Huang
# @ BSD-3-Clause License
"""Build the Ark-Picit client into distributables with PyInstaller.

Reads the project metadata and the ``[tool.build]`` build definition from
``pyproject.toml``, then produces two artifacts under ``build/dist/``:

- ``ark-picit-v<version>.exe``  — single-file executable (one-click run)
- ``ark-picit-v<version>.zip``  — extracted-directory build, zipped (portable)

Run from the repository root:

    uv run python tools/build.py
"""

from __future__ import annotations

import os
import os.path as osp
import shutil
import subprocess
import sys
import time
import tomllib
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _get_proj_info() -> dict:
    try:
        with (ROOT / "pyproject.toml").open("rb") as f:
            config = tomllib.load(f)["project"]
        return {
            "name": config["name"],
            "version": config["version"],
            "description": config["description"],
            "author": config["authors"][0]["name"],
            "license": config.get("license", ""),
        }
    except (KeyError, tomllib.TOMLDecodeError) as arg:
        print(f"x Required field missing or pyproject.toml invalid: {arg}")
        raise


def _get_build_def() -> dict:
    try:
        with (ROOT / "pyproject.toml").open("rb") as f:
            config = tomllib.load(f)["tool"]["build"]
        return {
            k: (v.replace("$project$", str(ROOT)) if isinstance(v, str) else v)
            for k, v in config.items()
        }
    except (KeyError, tomllib.TOMLDecodeError) as arg:
        print(f"x Failed to parse [tool.build] definition: {arg}")
        raise


def _exec(cmd: list[str]) -> None:
    rst = subprocess.run(cmd)
    if rst.returncode == 0:
        print(f"\n[Done] <- {' '.join(cmd)}")
    else:
        print(f"\n[Error] <- {' '.join(cmd)}")
        print(f"x Execution failed! Returned code: {rst.returncode}")
        sys.exit(1)


def _generate_version_file(proj_info: dict, build_dir: Path) -> Path:
    """Write the Windows version resource consumed by ``--version-file``."""
    version_file = build_dir / "version.txt"
    version_ints = f"({proj_info['version'].replace('.', ',')},0)"
    version_file.write_text(
        f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
filevers={version_ints},
prodvers={version_ints},
mask=0x3f,
flags=0x0,
OS=0x4,
fileType=0x1,
subtype=0x0,
date=(0,0)
),
  kids=[
StringFileInfo([
  StringTable(
    u'040904B0',
    [StringStruct(u'CompanyName', u'{proj_info["author"]}'),
    StringStruct(u'FileDescription', u'{proj_info["description"]}'),
    StringStruct(u'FileVersion', u'{proj_info["version"]}'),
    StringStruct(u'LegalCopyright', u'Copyright (c) {proj_info["author"]} @{proj_info["license"]} License'),
    StringStruct(u'ProductName', u'Ark-Picit'),
    StringStruct(u'ProductVersion', u'{proj_info["version"]}')])
  ])
])
""",
        encoding="utf-8",
    )
    return version_file


def _generate_build_meta(version: str, default_api_server: str, build_dir: Path) -> Path:
    """Write the metadata module injected into the bundle at ``src/app/_build_meta.py``."""
    build_meta = build_dir / "_build_meta.py"
    server_line = f'default_api_server = "{default_api_server}"\n' if default_api_server else ""
    build_meta.write_text(
        f'"""Build-time metadata, generated by tools/build.py. Do not edit."""\n\n'
        f'__version__ = "{version}"\n'
        f"{server_line}",
        encoding="utf-8",
    )
    return build_meta


def _split_source_dest(value: str) -> tuple[str, str]:
    """Split a ``source:dest`` pair, ignoring the ``D:\\`` drive prefix."""
    import re

    for match in re.finditer(r"(^\w:[/\\])|[:;]", value):
        if not match[1]:  # a real separator, not the drive letter
            return value[: match.start()], value[match.end():]
    raise ValueError(f"Missing ':' separator in add-data item: {value}")


#: OpenCV bundles a video codec backend (opencv_videoio_ffmpeg*.dll, ~29 MB)
#: that is only loaded by cv2.VideoCapture/VideoWriter. Ark-Picit never uses
#: video, so the DLL is dropped from the bundle to shrink the distributables.
_EXCLUDED_BINARIES = ("opencv_videoio_ffmpeg",)


def _write_spec(
    build_def: dict,
    proj_info: dict,
    name: str,
    version_file: Path,
    datas: list[tuple[str, str]],
    spec_path: Path,
    onefile: bool,
) -> None:
    """Write a PyInstaller spec that drops the excluded binaries."""
    entry = osp.normpath(build_def["entry"]).replace("\\", "/")
    datas_str = ",\n        ".join(
        f"('{s.replace(chr(92), '/')}', '{d}')" for s, d in datas
    )
    excludes_str = " or ".join(f"'{e}' in x[0]" for e in _EXCLUDED_BINARIES)
    version = osp.normpath(str(version_file)).replace("\\", "/")
    if onefile:
        # Single-file build: everything is embedded into the executable.
        exe_block = f"""
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='{name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='{version}',
)
"""
    else:
        # Directory build: the executable is separate from the collected files.
        exe_block = f"""
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='{version}',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{name}',
)
"""
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(
        f"""# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['{entry}'],
    pathex=['{osp.dirname(entry)}'],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
# Drop unused OpenCV video I/O backend to shrink the bundle.
a.binaries = TOC(x for x in a.binaries if not ({excludes_str}))
pyz = PYZ(a.pure)
{exe_block}""",
        encoding="utf-8",
    )


def _build(proj_info: dict, build_dir: str) -> None:
    t1 = time.time()

    print("Removing build dir...")
    if osp.exists(build_dir):
        shutil.rmtree(build_dir)
    os.makedirs(build_dir)

    print("Generating version file and build metadata...")
    build_def = _get_build_def()
    version_file = _generate_version_file(proj_info, Path(build_dir))
    default_server = build_def.get("default_api_server", "")
    build_meta = _generate_build_meta(proj_info["version"], default_server, Path(build_dir))

    name = f"{proj_info['name']}-v{proj_info['version']}"

    # Common data files; add-data source:dest pairs are separated by | (Ark-Unpacker style).
    datas: list[tuple[str, str]] = []
    for item in build_def.get("add-data", "").split("|"):
        if not item:
            continue
        src, dest = _split_source_dest(item)
        datas.append((src, dest))
    # Inject the generated metadata module next to src/app/dist.py.
    datas.append((str(build_meta), "src/app"))

    dist_dir = osp.join(build_dir, "dist")
    os.makedirs(dist_dir, exist_ok=True)

    log_level = build_def.get("log-level", "WARN")

    print("Running pyinstaller (single-file exe)...")
    spec_onefile = Path(build_dir) / "spec_onefile" / f"{name}.spec"
    _write_spec(build_def, proj_info, name, version_file, datas, spec_onefile, onefile=True)
    _exec([
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--log-level", log_level,
        "--distpath", dist_dir,
        "--workpath", osp.join(build_dir, "work_onefile"),
        str(spec_onefile),
    ])

    print("Running pyinstaller (extracted directory)...")
    spec_onedir = Path(build_dir) / "spec_onedir" / f"{name}.spec"
    _write_spec(build_def, proj_info, name, version_file, datas, spec_onedir, onefile=False)
    _exec([
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--log-level", log_level,
        "--distpath", dist_dir,
        "--workpath", osp.join(build_dir, "work_onedir"),
        str(spec_onedir),
    ])

    print("Zipping the extracted directory build...")
    folder = osp.join(dist_dir, name)
    zip_path = osp.join(dist_dir, f"{name}.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _dirs, files in os.walk(folder):
            for f in files:
                full = osp.join(root, f)
                zf.write(full, osp.join(name, osp.relpath(full, folder)))
    shutil.rmtree(folder)

    print(f"√ Build finished in {round(time.time() - t1, 1)}s!")
    print(f"- Dist files see: {dist_dir}")
    for f in os.listdir(dist_dir):
        print(f"  - {f}")


if __name__ == "__main__":
    proj_info = _get_proj_info()
    build_dir = _get_build_def()["build-dir"]
    print(f"Project: {proj_info['name']}|{proj_info['version']}|{proj_info['author']}|{proj_info['license']}")
    print(f"Root: {ROOT}")
    print("")
    _build(proj_info, build_dir)
    exit(0)
